### ISSUE TITLE
Options params array

### ISSUE THREAD

**Issue by sbi-krisj** [peteward44/node-svn-ultimate#1]
Hello - Excellent utility!

I've noticed when including params array in optional options, that the params get appended twice to the cmd string passed into exec(). First in executeSvn() and a second time in execute(). Is this by design? When using the svn.log(), I'm including a range param (-r {date range..}), which when it is appended twice, causes SVN to return the same log twice. Ex. %svn log path -r {2015-4-21}:{2015-4-24} -r {2015-4-21}:{2015-4-24}

Thanks!

**Comment by peteward44** [comment]
Yes you are absolutely right, that's definitely an oversight and not be design. Fixed in 0.1.1

**Comment by ewerton-azevedo** [comment]
I need to get the log of reviews in a range ``svn log -r100:150``

``
const logData = await svnClient.commands.log(`${process.env.SVN_PATH}`, {"-r":"100:150"}, async function(err, data){
        return await data
    })
``

Is that the right way? I did not find a reference of how that option object should be

**Comment by ewerton-azevedo** [comment]
How can I get the commits by date range?
I am trying 
'''
        const revisions = {"range": '2019-08-29'+':'+'2019-09-02'}
return svnClient.commands.log(`${ config.svn.path }`, revisions, async function ( err, data )
'''
But I get this error:

'''
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:348:14)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:261:13)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
'''

**Comment by ewerton-azevedo** [comment]
I found the answer for my question...
My range object should have the "revision" property, not "range".

I checked the source code and found it at addExtraOptions.
Reading the complete code helped me to figure it out.
Excelente code, btw!
