### ISSUE TITLE
Deprecated graceful-fs

### ISSUE THREAD

**Issue by nqu0** [peteward44/node-svn-ultimate#4]
I have the following warning when installing node-svn-ultimate:
`npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.`
Any plans to follow the graceful-fs version?

**Comment by peteward44** [comment]
I've updated the dependency fs-extra which caused this warning, i have published v1.0.3

**Comment by nqu0** [comment]
Thanks you. It works.
