### ISSUE TITLE
Fails in Windows

### ISSUE THREAD

**Issue by macaihong2017** [peteward44/node-svn-ultimate#7]
Code:
const svnUltimate = require('node-svn-ultimate');
svnUltimate.commands.update('xxx', {username: 'xxx', password: 'xxx'}, function(err) {

        if (err) {
            console.log('err', err);
            return false;
        }

        console.log('Update complete');
    });

ERROR:
 Error: Command failed: C:\Windows\system32\cmd.exe /s /c "svn update https://svn.xxx.com/xxx --non-interactive --uername=xxx --password=xxx"

**Comment by chrisrymer** [comment]
Does this indicate that the package doesn't work with CMD.exe?

**Comment by peteward44** [comment]
I've used it on windows before with the default shell no problem. Try specifying a different shell with the shell option

**Comment by chrisrymer** [comment]
Ah ok good to know. Did you get you get your issue resolved?

**Comment by fbertini** [comment]
Hi, 

I actually have the same issue.
I'm trying this on Windows 10.

`const SvnClient = use('node-svn-ultimate')

// within a function
SvnClient.commands.checkout(repoUrl, '/tmp/tests',
            {
                trustServerCert: true,  // same as --trust-server-cert
                username: "user",
                password: "Password"
            },
            function (err) {
                console.log(err);
            });
`
I get the following error:
`
svn: E205000: Try 'svn help checkout' for more information
svn: E205000: Error parsing arguments
{ Error: Command failed: svn checkout  /tmp/tests --non-interactive --trust-server-cert --username=user --password=Password
svn: E205000: Try 'svn help checkout' for more information
svn: E205000: Error parsing arguments

    at ChildProcess.exithandler (child_process.js:273:12)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'svn checkout  /tmp/tests --non-interactive --trust-server-cert --username=user --password=Password ' }
`

**Comment by peteward44** [comment]
Try running the command from the command line and see if that sheds any light on the error
```
svn checkout /tmp/tests --non-interactive --trust-server-cert --username=user --password=Password 
```

**Comment by fbertini** [comment]
Hi!

I tried again after a new package install and it is working now. I have no idea why.
By the way, I'm trying this on Windows, and I see that /tmp/tests (the path I'm using for checking out) is considered as if it was C:\tmp\tests. 
Do I always have to use Unix like paths?

**Comment by peteward44** [comment]
Nope you can use whatever paths are appropriate for your platform. I would use the node.js ```path``` module to make your code as platform-independent as possible though, if you're checking out to a temporary directory you can use ```os.tmpdir()``` to get your operating system's temporary directory
