### ISSUE TITLE
Synchronous checkout?

### ISSUE THREAD

**Issue by Wandalen** [peteward44/node-svn-ultimate#9]
Is it possible to make synchronous checkout with the package?

**Comment by peteward44** [comment]
Several options here; you could either:

- Use a module that transforms async code to sync like https://www.npmjs.com/package/synchronize - i wouldn't recommend as it uses native modules and is a bit messy
- Fork this project and replace the .spawn() calls with .spawnSync()

**Comment by Wandalen** [comment]
I see. Thanks.
